// @generated by `pnpm gen:types` — do not edit manually

/*
 Generated by typeshare 1.13.4
*/

export interface AddTaskToProjectRequest {
	taskId: string;
}

export interface ChannelSettings {
	id: string;
	enabled: boolean;
	status: string;
	paired: boolean;
	pairingCode?: string;
	error?: string;
	hasCredentials: boolean;
	meta: Record<string, unknown>;
}

export interface ChannelListResponse {
	channels: ChannelSettings[];
}

export interface CreateProjectRequest {
	name: string;
	color?: string;
}

export interface GeneralSettings {
	language: string;
	themeMode: string;
	agentPromptAppend: string;
}

export interface ProviderSummary {
	id: string;
	configured: boolean;
}

export interface ModelSettings {
	activeProvider: string;
	model?: string;
	providers: ProviderSummary[];
}

export interface OkResponse {
	ok: boolean;
}

export interface PairingCodeResponse {
	code: string;
}

export interface PatchGeneralSettings {
	language?: string;
	themeMode?: string;
	agentPromptAppend?: string;
}

export interface PatchModelSettings {
	activeProvider?: string;
	model?: string;
}

export enum PermissionLevel {
	Deny = "deny",
	Ask = "ask",
	Allow = "allow",
}

export interface PatchPermissionsSettings {
	fsRead?: PermissionLevel;
	fsWrite?: PermissionLevel;
	cmdRun?: PermissionLevel;
	netHttp?: PermissionLevel;
}

export interface PatchProjectRequest {
	name?: string;
	color?: string;
}

export interface PermissionsSettings {
	fsRead: PermissionLevel;
	fsWrite: PermissionLevel;
	cmdRun: PermissionLevel;
	netHttp: PermissionLevel;
}

export interface Project {
	id: string;
	name: string;
	color: string;
	createdAt: number;
}

export interface ProjectSummary {
	id: string;
	name: string;
	color: string;
	taskCount: number;
}

export interface ProviderListItem {
	id: string;
	name: string;
	configured: boolean;
}

export interface PutProviderCredentials {
	apiKey: string;
}

export interface RuntimeAppStats {
	cpuPercent: number;
	memoryMb: number;
	processCount: number;
}

export interface RuntimeSystemStats {
	totalMemMb: number;
	freeMemMb: number;
	loadavg1m: number;
}

export interface RuntimeStats {
	ts: number;
	app: RuntimeAppStats;
	system: RuntimeSystemStats;
}

export interface Schedule {
	id: string;
	prompt: string;
	frequency: string;
	cronExpr: string;
	enabled: boolean;
	lastRunAt: number;
	nextRunAt: number;
	createdAt: number;
}

export interface ScheduleListResponse {
	schedules: Schedule[];
}

export interface TaskCancelResponse {
	id: string;
	status: string;
}

export interface TaskContinueRequest {
	prompt: string;
	attachments?: string[];
}

export interface TaskCreateRequest {
	prompt: string;
	attachments?: string[];
	mode?: string;
}

export interface TaskCreatedResponse {
	id: string;
	status: string;
}

export interface TaskStepResponse {
	tool: string;
	arguments?: string;
	result?: string;
	error?: string;
}

export interface TaskMessageResponse {
	role: string;
	content: string;
	steps?: TaskStepResponse[];
	createdAt: string;
	error?: boolean;
}

export interface TaskResponse {
	id: string;
	status: string;
	prompt: string;
	summary?: string;
	error?: string;
	createdAt: string;
	updatedAt: string;
	projectId?: string;
	steps?: TaskStepResponse[];
	messages?: TaskMessageResponse[];
}

export interface TaskListResponse {
	items: TaskResponse[];
	total: number;
}

export interface ToolApprovalRequest {
	requestId: string;
	approved: boolean;
}

export enum CapabilityId {
	FsRead = "fs.read",
	FsWrite = "fs.write",
	CmdRun = "cmd.run",
	NetHttp = "net.http",
}

export enum ChannelId {
	Telegram = "telegram",
	Whatsapp = "whatsapp",
	Discord = "discord",
	Signal = "signal",
	Slack = "slack",
}

export enum ChannelStatus {
	Disconnected = "disconnected",
	Connecting = "connecting",
	Connected = "connected",
	Error = "error",
}

export enum LanguageCode {
	En = "en",
	Es = "es",
}

export enum ModeSource {
	Inferred = "inferred",
	Manual = "manual",
}

export enum ProviderId {
	Chatgpt = "chatgpt",
	Claude = "claude",
	Deepseek = "deepseek",
	Kimi = "kimi",
	Glm = "glm",
	Minimax = "minimax",
	Openrouter = "openrouter",
	Gemini = "gemini",
	Nvidia = "nvidia",
	Ollama = "ollama",
}

export enum ScheduleFrequency {
	Daily = "daily",
	Weekly = "weekly",
	Custom = "custom",
}

export enum TaskMode {
	Agent = "agent",
}

export enum TaskSource {
	Desktop = "desktop",
	Telegram = "telegram",
	Discord = "discord",
	Slack = "slack",
	Whatsapp = "whatsapp",
	Signal = "signal",
}

export enum TaskStatus {
	Planning = "planning",
	Pending = "pending",
	Running = "running",
	Completed = "completed",
	Failed = "failed",
	Cancelled = "cancelled",
}

export enum ThemeMode {
	System = "system",
	Light = "light",
	Dark = "dark",
	Midnight = "midnight",
	Forest = "forest",
}

